"""
Axon Factory Client - HTTP client for Axon 88 Builder v1 integration.

Handles communication between AXON Agency (Replit) and the local factory (Axon 88/Jetson).
"""

import httpx
from typing import Optional
from pydantic import BaseModel
from loguru import logger
from app.core.config import settings
from app.models.orders import Order


class AxonFactoryBuildResult(BaseModel):
    """Result of a build request to Axon 88 factory."""
    success: bool
    product_path: Optional[str] = None
    log_path: Optional[str] = None
    construido_en: Optional[str] = None
    error_message: Optional[str] = None
    raw_response: Optional[dict] = None
    
    # Builder v2 fields
    deliverable_dir: Optional[str] = None
    zip_path: Optional[str] = None
    qa: Optional[dict] = None  # {status, messages, checked_files}


class AxonFactoryClient:
    """
    HTTP client for Axon 88 Builder v1.
    
    Delegates product construction to the local factory via:
    POST {AXON_CORE_API_BASE}/factory/build-local
    
    Configuration (via environment variables):
    - AXON_CORE_ENABLED: Enable/disable factory integration
    - AXON_CORE_API_BASE: Base URL of Axon 88 control-api (via Cloudflare tunnel)
    - AXON_CORE_API_TOKEN: Optional auth token
    """
    
    def __init__(self):
        self.enabled = settings.axon_core_enabled
        self.base_url = settings.axon_core_api_base
        self.api_token = settings.axon_core_api_token
        self.timeout = 120.0  # 2 minutes for build requests
        
        # Log configuration at startup
        if self.enabled:
            logger.info(f"AxonFactoryClient initialized - base_url={self.base_url}")
        else:
            logger.info("AxonFactoryClient disabled (AXON_CORE_ENABLED=false)")
    
    async def build_product(
        self,
        order: Order,
        plan: dict,
        agent_blueprint: Optional[dict] = None
    ) -> AxonFactoryBuildResult:
        """
        Request product construction in Axon 88 factory.
        
        Args:
            order: Order object with product details
            plan: JSON plan generated by Orders Orchestrator
            agent_blueprint: Optional blueprint specification (FASE 3.B - forwarded to Axon 88)
            
        Returns:
            AxonFactoryBuildResult with success status and paths
            
        Flow:
            1. Validate configuration
            2. POST to /factory/build-local with order + plan
            3. Parse response with product_path and log_path
            4. Return result object
            
        Error Handling:
            - Configuration errors → success=False, error_message
            - Network/timeout errors → success=False, error_message
            - HTTP 4xx/5xx → success=False, error_message
            - Invalid JSON → success=False, error_message
        """
        
        # Validate configuration
        if not self.enabled:
            logger.warning("Axon Factory integration disabled (AXON_CORE_ENABLED=false)")
            return AxonFactoryBuildResult(
                success=False,
                error_message="Axon Factory integration is disabled"
            )
        
        if not self.base_url:
            logger.error("AXON_CORE_API_BASE not configured")
            return AxonFactoryBuildResult(
                success=False,
                error_message="AXON_CORE_API_BASE not configured"
            )
        
        # Prepare request payload
        payload = {
            "order": {
                "order_id": order.id,
                "order_number": order.order_number,
                "tipo_producto": order.tipo_producto,
                "nombre_producto": order.nombre_producto,
                "datos_cliente": order.datos_cliente,
                "prioridad": order.prioridad
            },
            "plan": plan
        }
        
        # FASE 3.B: Include agent_blueprint if present (optional, backward compatible)
        if agent_blueprint:
            payload["agent_blueprint"] = agent_blueprint
            # Use structured logging to avoid loguru formatting issues with braces
            logger.info(
                "📋 AgentBlueprint included in build request - type={agent_type}, version={version}",
                agent_type=agent_blueprint.get('agent_type', 'unknown'),
                version=agent_blueprint.get('version', 'unknown')
            )
        
        # Prepare headers
        headers = {"Content-Type": "application/json"}
        if self.api_token:
            headers["Authorization"] = f"Bearer {self.api_token}"
        
        endpoint = f"{self.base_url}/factory/build-local"
        
        logger.info(
            f"Requesting build in Axon 88 - order={order.order_number}, "
            f"tipo={order.tipo_producto}, endpoint={endpoint}"
        )
        
        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.post(
                    endpoint,
                    json=payload,
                    headers=headers
                )
                
                # Log response status
                logger.info(
                    f"Axon 88 build response - status={response.status_code}, "
                    f"order={order.order_number}"
                )
                
                # Handle HTTP errors
                if response.status_code >= 400:
                    error_msg = f"HTTP {response.status_code}: {response.text[:200]}"
                    logger.error(
                        f"Axon 88 build failed - order={order.order_number}, "
                        f"error={error_msg}"
                    )
                    return AxonFactoryBuildResult(
                        success=False,
                        error_message=error_msg,
                        raw_response={"status_code": response.status_code, "text": response.text[:500]}
                    )
                
                # Parse JSON response
                try:
                    data = response.json()
                except Exception as e:
                    logger.error(
                        f"Invalid JSON from Axon 88 - order={order.order_number}, "
                        f"error={str(e)}"
                    )
                    return AxonFactoryBuildResult(
                        success=False,
                        error_message=f"Invalid JSON response: {str(e)}",
                        raw_response={"text": response.text[:500]}
                    )
                
                # Extract paths from response
                # Expected response format (Axon 88 Builder v1/v2):
                # {
                #   "success": true,
                #   "error": null,
                #   "product_path": "/home/axon88/factory/products/ORD-2025-001_autopilot_whatsapp",
                #   "log_path": "/home/axon88/factory/logs/orders.log",
                #   "construido_en": "2025-11-15T01:56:31.106933",
                #   "deliverable_dir": "/home/axon88/factory/deliverables/ORD-2025-001_autopilot_whatsapp",  # Builder v2 only
                #   "zip_path": "/home/axon88/factory/deliverables/ORD-2025-001_autopilot_whatsapp/ORD-2025-001_autopilot_whatsapp.zip",  # Builder v2 only
                #   "qa": {"status": "ok", "messages": [...], "checked_files": [...]}  # Builder v2 only
                # }
                
                success = data.get("success", False)
                product_path = data.get("product_path")
                log_path = data.get("log_path")
                construido_en = data.get("construido_en")
                error_message = data.get("error")
                
                # Extract Builder v2 fields (optional - backward compatible)
                deliverable_dir = data.get("deliverable_dir")
                zip_path = data.get("zip_path")
                qa = data.get("qa")  # {status, messages, checked_files}
                
                # Log full response for debugging
                logger.info(f"Axon 88 raw response: {data}")
                
                if success:
                    logger.success(
                        f"Axon 88 build successful - order={order.order_number}, "
                        f"product_path={product_path}, construido_en={construido_en}"
                    )
                else:
                    logger.warning(
                        f"Axon 88 build reported failure - order={order.order_number}, "
                        f"error={error_message}"
                    )
                
                return AxonFactoryBuildResult(
                    success=success,
                    product_path=product_path,
                    log_path=log_path,
                    construido_en=construido_en,
                    error_message=error_message,
                    raw_response=data,
                    deliverable_dir=deliverable_dir,
                    zip_path=zip_path,
                    qa=qa
                )
                
        except httpx.TimeoutException as e:
            logger.error(
                f"Timeout calling Axon 88 - order={order.order_number}, "
                f"timeout={self.timeout}s, error={str(e)}"
            )
            return AxonFactoryBuildResult(
                success=False,
                error_message=f"Request timeout after {self.timeout}s"
            )
            
        except httpx.NetworkError as e:
            logger.error(
                f"Network error calling Axon 88 - order={order.order_number}, "
                f"error={str(e)}"
            )
            return AxonFactoryBuildResult(
                success=False,
                error_message=f"Network error: {str(e)}"
            )
            
        except Exception as e:
            logger.error(
                f"Unexpected error calling Axon 88 - order={order.order_number}, "
                f"error={str(e)}"
            )
            return AxonFactoryBuildResult(
                success=False,
                error_message=f"Unexpected error: {str(e)}"
            )


# Singleton instance
_axon_factory_client: Optional[AxonFactoryClient] = None


def get_axon_factory_client() -> AxonFactoryClient:
    """Get or create singleton AxonFactoryClient instance."""
    global _axon_factory_client
    if _axon_factory_client is None:
        _axon_factory_client = AxonFactoryClient()
    return _axon_factory_client
