import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { CheckCircle2, Circle, FileText, Workflow, Settings, MessageSquare, Plug } from "lucide-react"

interface AgentArtifactsCardProps {
  deliverableMetadata?: {
    order_number?: string
    tipo_producto?: string
    qa_status?: string | null
    construido_en?: string
    archivos?: string[]
  } | null
}

interface ArtifactStatus {
  name: string
  icon: React.ComponentType<{ className?: string }>
  detected: boolean
  description: string
}

export function AgentArtifactsCard({ deliverableMetadata }: AgentArtifactsCardProps) {
  if (!deliverableMetadata || !deliverableMetadata.archivos) {
    return (
      <Card className="border-dashed">
        <CardHeader>
          <CardTitle className="text-sm font-medium">Agent Artifacts</CardTitle>
          <CardDescription className="text-xs">
            No deliverable generated yet. Artifacts will appear after Agent Builder completes.
          </CardDescription>
        </CardHeader>
      </Card>
    )
  }

  const files = deliverableMetadata.archivos || []
  
  const detectArtifact = (patterns: string[]): boolean => {
    return files.some(file => 
      patterns.some(pattern => 
        file.toLowerCase().includes(pattern.toLowerCase())
      )
    )
  }

  const artifacts: ArtifactStatus[] = [
    {
      name: "Agent Specification",
      icon: FileText,
      detected: detectArtifact(['AGENT_SPEC', 'agent/spec', 'spec.md']),
      description: "Complete agent system specification"
    },
    {
      name: "Conversation Flows",
      icon: Workflow,
      detected: detectArtifact(['flow', 'n8n', 'automation']),
      description: "n8n workflows and conversation flows"
    },
    {
      name: "Channel Configuration",
      icon: Settings,
      detected: detectArtifact(['config', 'whatsapp', 'channel']),
      description: "WhatsApp and channel settings"
    },
    {
      name: "Agent Prompts",
      icon: MessageSquare,
      detected: detectArtifact(['prompt', 'system.txt', 'examples']),
      description: "Base prompts and examples"
    },
    {
      name: "Integration Manifests",
      icon: Plug,
      detected: detectArtifact(['integration', 'vapi', 'webhook', 'manifest']),
      description: "VAPI, n8n, and webhook configs"
    }
  ]

  const detectedCount = artifacts.filter(a => a.detected).length
  const allDetected = detectedCount === artifacts.length

  return (
    <Card>
      <CardHeader>
        <div className="flex items-start justify-between">
          <div className="space-y-1">
            <CardTitle className="text-sm font-medium">Agent Artifacts</CardTitle>
            <CardDescription className="text-xs">
              System generated by Agent Builder in Axon 88
            </CardDescription>
          </div>
          {allDetected && (
            <CheckCircle2 className="h-4 w-4 text-green-400" />
          )}
        </div>
      </CardHeader>
      <CardContent className="space-y-3">
        <div className="text-xs text-muted-foreground mb-2">
          {detectedCount} of {artifacts.length} artifacts detected
        </div>
        
        <div className="space-y-2">
          {artifacts.map((artifact, idx) => {
            const Icon = artifact.icon
            const StatusIcon = artifact.detected ? CheckCircle2 : Circle
            
            return (
              <div
                key={idx}
                className={`flex items-start gap-3 p-2 rounded-md transition-colors ${
                  artifact.detected 
                    ? 'bg-green-500/10 border border-green-500/20' 
                    : 'bg-muted/50 border border-transparent'
                }`}
              >
                <Icon className={`h-4 w-4 mt-0.5 flex-shrink-0 ${
                  artifact.detected ? 'text-green-400' : 'text-muted-foreground'
                }`} />
                <div className="flex-1 space-y-0.5">
                  <div className="flex items-center gap-2">
                    <StatusIcon className={`h-3.5 w-3.5 ${
                      artifact.detected ? 'text-green-400' : 'text-muted-foreground'
                    }`} />
                    <span className={`text-xs font-medium ${
                      artifact.detected ? 'text-foreground' : 'text-muted-foreground'
                    }`}>
                      {artifact.name}
                    </span>
                  </div>
                  <p className="text-xs text-muted-foreground pl-5">
                    {artifact.description}
                  </p>
                </div>
              </div>
            )
          })}
        </div>

        {allDetected && (
          <div className="pt-2 mt-2 border-t">
            <p className="text-xs text-green-400 font-medium flex items-center gap-2">
              <CheckCircle2 className="h-3.5 w-3.5" />
              Complete agent system ready
            </p>
          </div>
        )}

        {!allDetected && detectedCount > 0 && (
          <div className="pt-2 mt-2 border-t">
            <p className="text-xs text-muted-foreground">
              Partial artifacts detected. Some components may be in progress.
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
